### ISSUE TITLE
[Track UI] Unknown "En" Concept shown as Mastered

### ISSUE THREAD

**Issue by mohmad-null** [exercism/python#2849] opened 2022-01-10 14:11 UTC
Not sure if this is a Python specific thing or an exercism thing.

On this https://exercism.org/tracks/python - I'm seeing this:
![image](https://user-images.githubusercontent.com/22342282/148779562-0e2e7316-f048-4476-b76c-d7eed17e0381.png)

Problem is, there is no "En" Concept as far as I can see. And looking at the tracks page, only the Ba(sic) is all-completed (I assume that's what "mastered" means).

**Comment by IsaacG** [comment] 2022-01-11 01:22
The Python repo is used for Python documentation, concepts, exercises, etc. I suspect you want to post that issue to the exercism/exercism repo.

**Comment by kotp** [comment] 2022-01-11 03:55
@ErikSchierboom I think you can move this, it is likely in the wrong one repository as @IsaacG noted above.

**Comment by ErikSchierboom** [comment] 2022-01-11 07:15
@mohmad-null What is your Exercism username?

@IsaacG @kotp Whether it is in the wrong repository is something I'll dig into. It _might_ not be.

**Comment by kotp** [comment] 2022-01-11 08:04
Thanks @ErikSchierboom

**Comment by BethanyG** [comment] 2022-01-11 21:43
@mohmad-null - Did you by chance complete either `Bank Account` or `Log-Levels`?  Those are the two (currently) according to our `config.json` that are connected to the `Enums` concept.....which I am taking a wild guess might map to **[En]**.

`Log-Levels` was live briefly, and then we set it back to `wip`, but if in that time you completed it and `Bank-Account`, the site may still be reading it as completed and counting toward the "mastered" count.

@ErikSchierboom  -- snips from `config.json` below:

![image](https://user-images.githubusercontent.com/5923094/149025295-d9dbfd61-6215-4014-9486-9759e2511f4d.png)
![image](https://user-images.githubusercontent.com/5923094/149025324-5acfa936-4faf-4a82-8d03-1bd6badda732.png)


Although there might be something going on with how that category is being calculated in addition to just the practices field.  In my account, I show **[Di**] (_dictionaries, I am assuming_) as mastered, but I have yet to complete the last two associated practice exercises:

![image](https://user-images.githubusercontent.com/5923094/149025583-de00e2f6-f514-40b5-b29e-31575c887f4b.png)

and the concept tree:

![image](https://user-images.githubusercontent.com/5923094/149025692-05e49d47-d8ef-40d4-bda7-125838e63fbc.png)


Note also that my "Mastered" does not show **[Se]** (_sets_), although the tree shows I've completed all but one exercise there.

**Comment by BethanyG** [comment] 2022-01-11 21:47
Follow-on to say that in my account **[An]** (_I have no idea what this maps to_) and **[Fu]** (_functions??_) also show as "Mastered", but we don't currently have concepts live for either - and looking at which exercises are tagged to practice `functions`, I have yet to complete several of them.

**Comment by ErikSchierboom** [comment] 2022-01-12 07:31
Thanks for the detailed analysis @BethanyG. We'll take a look.

**Comment by ErikSchierboom** [comment] 2022-01-12 11:43
@BethanyG I've checked in the database, and your concepts are:

```
["anonymous-functions", "collections", "dict-methods", "functional-tools"]
```

Does that make sense for you?

**Comment by BethanyG** [comment] 2022-01-12 21:04
🤔 

Yes.  I've completed the related practice exercises.  However, none of them have live concept exercises.

* `functional-tools` -- there are  2 exercises that practice that (`Matrix` and `Largest Series Product`)
* `anonymous-functions` -- there are only two exercises that practice that (`Tournament` and `Largest Series Product`)
* `collections` -- there are 4 exercises that practice that (`Word-Count`, `Tournament`, `Book-Store` and `Grade School`)
* `dict-methods` -- there are 8 exercises that practice that (`Robot Simulator`, `ETL`, `Meetup`, `Allergies`, `Protein-Translation`, `Tournament`,`Grade School`, and `Scrabble-Score`)

So three observations -- 

1.  Serious confusion as to what `mastered` means vs `learned`.  One appears to be for `concept`, the other for `practices`, but I don't think that's really explained or indicated anywhere - or anywhere obvious.
2.  There are no tooltips/hovers on either categories **[`<concept>`]** two-letter abbreviations (at least not on the Python track currently), so no easy way to tell what the abbreviation relates to.  If you click on either box in the UI, you are taken to the concept tree, which implies that both are connected to completing concept exercises and the practice exercises linked to them.  But with Pythons tree incomplete, many exercises aren't represented there.
3.   The re-use of two letter abbreviations to represent unrelated concepts is really confusing.  Example is **[Co]** being used for `Collections`, `Conditionals` and (possibly?) `Comparisons`.

**Comment by BethanyG** [comment] 2022-01-15 16:52
@mohmad-null -- do these explanations make sense?  Can I close this issue?

**Comment by BethanyG** [comment] 2022-01-20 19:30
@ErikSchierboom  -- is this something we should transfer, or close?  Feels to me like a by-product of the fact that Python has prerequisites and practices defined that are not (yet) directly linked to live concepts/concept exercises.

But there is also some confusing UI things (_that I'm sure have already been logged -- I just can't find them_).

**Comment by ErikSchierboom** [comment] 2022-01-25 07:36
> Serious confusion as to what mastered means vs learned. One appears to be for concept, the other for practices, but I don't think that's really explained or indicated anywhere - or anywhere obvious.

I think this is a valid remark and the cause of most of the confusion, right? 

> But there is also some confusing UI things (that I'm sure have already been logged -- I just can't find them).

This definitely warrants a separate issue. Feel free to open a new open if you can't find the older issue, we'll find the older one at some point.

**Closed** 2022-05-06 18:32 UTC
