### ISSUE TITLE
Issue with markdown exercise in python

### ISSUE THREAD

**Issue by vijayshan** [exercism/python#2979] opened 2022-03-14 07:17 UTC
All tests pass when the exercise is downloaded. I think the solution was accidentally presented as the question.

**Comment by BethanyG** [comment] 2022-03-14 08:31
Hi @vijayshan 👋🏽 

If you read the [instructions](https://github.com/exercism/python/blob/main/exercises/practice/markdown/.docs/instructions.md),  they state that this is a **_refactoring_** exercise.  The intent was to give you messy and complex code that passes the tests and have you clean up and refactor it to be clearer and cleaner and _still_ pass the tests.  The code that is in the file currently should be re-written/improved by you.  😄

**Comment by kotp** [comment] 2022-03-14 21:30
Closing as it is by design.  See response to [comment here].

[comment here]: https://github.com/exercism/python/commit/32c96c98ada60893d847bbaf448e5b25cc7486e8#commitcomment-68619754

**Comment by BethanyG** [comment] 2022-03-14 21:32
@kotp  -- please don't close issues in this repo unless the OP has responded, or we've waited an interval for the OP to do so.  Thanks!

**Comment by BethanyG** [comment] 2022-03-14 21:42
I reopened it.

**Comment by BethanyG** [comment] 2022-03-17 06:45
@vijayshan  - closing this issue.  Please reopen this one or submit a new one if you have additional questions or problems.

**Closed by BethanyG** 2022-03-17 06:45 UTC
