### ISSUE TITLE
Unclear TODO in `guidos-gorgeous-lasagna`

### ISSUE THREAD

**Issue by pranasziaukas** [exercism/python#2576] opened 2021-09-13 09:06 UTC
https://github.com/exercism/python/blob/e0404a284548924d373bf3c357283257164410f6/exercises/concept/guidos-gorgeous-lasagna/lasagna.py#L2

I approached this exercise as a student for the first time, so should not be biased.

It was not immediately clear to me that `PREPARATION_TIME` means the preparation time of a single layer of lasagna - it is not explicitly described in code or instructions. Furthermore, it is not used in tests in any way.

I'd suggest either:
1. Drop the TODO line altogether as it is not technically required.
2. Edit the instructions so that it's clear that `preparation_time_in_minutes` should use `PREPARATION_TIME`.

Happy to submit a PR.

**Comment by BethanyG** [comment] 2021-09-13 09:37
It is true that we don't explicitly test for the use of `PREPARATION_TIME`, although our `exemplar.py` file does use that constant.  We do have a [hint](https://github.com/exercism/python/blob/main/exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md) that declaring a constant for the prep time might be a good idea to avoid using "magic numbers".  
The TODO was intended as an extra "nudge" in that same direction.  

However, it is not required to declare _that_ particular constant to complete this exercise (_we just test for the first one_).  Hence, we may want to make that comment a suggestion:

`# Consider defining a 'PREPARATION_TIME' constant.`

or 

 `# You may want to define a 'PREPARATION_TIME' constant here.`

Another strategy would be to **_require_**  that the student declare this additional constant.  In that case we would want to change the directions, and add a test for `PREPARATION_TIME`.  But I don't know that we really want to do that.  We want students to be aware of how to declare and use "constants" in python -- but they don't always **have to** to write correct code.  Here, it's a nice option for maintainability -- but it isn't strictly _necessary_.

So I think I am in favor of changing the comment, but leaving the instructions and tests as they are for now.

**Comment by pranasziaukas** [comment] 2021-09-13 10:07
Thanks for the feedback @BethanyG.


> It is true that we don't explicitly test for the use of `PREPARATION_TIME`, although our `exemplar.py` file does use that constant. We do have a [hint](https://github.com/exercism/python/blob/main/exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md) that declaring a constant for the prep time might be a good idea to avoid using "magic numbers".

True, these make it pretty clear about the usage of `PREPARATION_TIME`. However, neither the hints nor the `exemplar.py` are normally looked at before approaching the problem independently.


> Hence, we may want to make that comment a suggestion:
> `# Consider defining a 'PREPARATION_TIME' constant.`

I like it! The only thing is, it still does not make it really clear that the `PREPARATION_TIME` is about the time to prepare a single layer of lasagna. That is, unless we place it next to the `preparation_time_in_minutes` TODO (it's the function that returns `PREPARATION_TIME * number_of_layers`). Then the suggested intent and the implementation would be more intuitive IMO.
What do you think?

**Comment by BethanyG** [comment] 2021-09-13 10:36
>The only thing is, it still does not make it really clear that the PREPARATION_TIME is about the time to prepare a single layer of lasagna. That is, unless we place it next to the preparation_time_in_minutes TODO (it's the function that returns PREPARATION_TIME * number_of_layers). Then the suggested intent and the implementation would be more intuitive IMO.

I know this may sound silly, but the only reason I wouldn't put the note only with the note about the function is that I want to make sure students put constants at the top of a file mostly (_yes - I know there are exceptions to that, but...._).

How about something like the following:
`# Consider defining a 'PREPARATION_TIME' constant `
`# equal to the time it takes to prepare a single layer.`

And then under the `preparation_time_in_minutes` TODO:
`# Consider using PREPARATION_TIME in this function.`

Does that work?

**Comment by pranasziaukas** [comment] 2021-09-14 07:55
SGTM

**Comment by BethanyG** [comment] 2021-09-14 15:15
Thank you again for logging this, and for your thoughtful discussion.  😄   Since the PR has merged, I am closing this as done.

**Closed by BethanyG** 2021-09-14 15:15 UTC
