### ISSUE TITLE
add directory Lapindrome in exercises/

### ISSUE THREAD

**Issue by Meg2tron** [exercism/python#930] opened 2017-10-15 17:28 UTC
adding **lapindrome.py** and **example.py** in `python/exercises/Lapindrome`

**Comment by m-a-ge** [comment] 2017-10-15 18:14
From the issue title or description I can't understand what the issue is or what you want to add.
Please clarify

**Comment by Meg2tron** [comment] 2017-10-15 18:36
@m-a-ge  the given program in  ** /exercises/Lapindrome** is used to check weather the given number is lapindrome or not i.e. it divides the given strings in two equal parts and then check the frequency of character in both halves of string . If the frequency of characters are equal then it is lapindrome  else not

**Comment by tbhaxor** [comment] 2017-10-15 18:38
@m-a-ge he added a python file `lapindrome.py` in **/exercises/Lapindrome**

## What is lapindrome ?
_Lapindrome is defined as a string which when split in the middle, gives two halves having the same characters and same frequency of each character. If there are odd number of characters in the string, we ignore the middle character and check for lapindrome_

**Comment by Meg2tron** [comment] 2017-10-15 18:40
@tbhaxor thanx for giving the proper defination I am thankful of you

**Comment by m-a-ge** [comment] 2017-10-15 19:00
So, looks like it's new exercise suggestion. 
Anyhow, every exercise should have a test suite and `README.md` file. 
Moreover, it's better to suggest new exercises in https://github.com/exercism/problem-specifications first

**Comment by N-Parsons** [comment] 2017-10-31 11:35
I'm going to close this issue and suggest that it should be raised in [exercism/problem-specifications](https://github.com/exercism/problem-specifications) instead if you still think that this exercise to be added. I could see this exercise being valuable as an early exercise, but I think it deserves proper discussion in the [exercism/problem-specifications](https://github.com/exercism/problem-specifications) repo first.

**Closed by N-Parsons** 2017-10-31 11:35 UTC
