### ISSUE TITLE
Exercise named series:  Poor Test Cases ?

### ISSUE THREAD

**Issue by AtelesPaniscus** [exercism/python#1109] opened 2017-11-15 11:41 UTC
The README for this simple exercise reads:

> Given a string of digits, output all the contiguous substrings of length n in that string.

For "49142" you might reason the substrings of length n are ["491", "914", "142"].  You would be wrong.

If you just look at the README instead of actually reading it, you might be forgiven for thinking the answer that is wanted is:  [491, 914, 142].  You would be wrong again.

Someone please explain how [[4, 9, 1], [9, 1, 4], [1, 4, 2]] is an appropriate answer in any programming language let alone Python.

Note:  this is not a new exercise and there appears to be no 'canonical' data to blame.

This exercise illustrates a more general point.

In the real world, people code to pass the tests because they don't have access to the requirements (because if they did it wouldn't help).  Shame.  For Exercism exercises would expect (and I hope you would agree) the student should be able to 'reason about' the problem and design a solution without having to study the test cases.  (Studying the test case may be useful to debug a solution but should not be necessary to design it.)

This clearly isn't the case for this exercise but there are others with incomplete problem statements that more or less oblige the student to study the test cases to figure out what is wanted.  I fear this is encouraging students to glance at the read me and then study the test cases.  They are learning to reason about the solutions, not the problem (arghhh the engineering mentality).

Consider this exercise's problem statement again.  Would the output for ("123123", 3) contain "123" twice or only once ?

I infer twice and, if I were wrong, I would expect at least one test case to fail as a consequence.  There is no test case for this so my solution would pass anyway and so would those of all the students who never reasoned about this.

What about the order in which substrings are output ?  I infer that since it is not mentioned it is unimportant.  Wrong.

I would like to suggest that the order in which substrings are output is not an implementation detail but more likely a side-effect of how the student reasoned about the problem.  Perfectly good reasoning could lead to a solution that fails all tests and forces a redesign.  For simple Exercism exercises like this, this should just not be possible because it is possible to write a complete enough README.

**Comment by N-Parsons** [comment] 2017-11-20 11:50
Thanks for raising this as an issue. It definitely seems like unexpected behaviour, especially since the description explicitly says to return substrings. I'll rework it now and submit my changes upstream to `problem-specifications` - I'd welcome your comments on my PR when it's created.

**Comment by AtelesPaniscus** [comment] 2017-11-21 10:04
Yes, love to see your PR when it is created.

**Comment by m-a-ge** [comment] 2017-12-25 20:45
Hm, I don't like when bot is closing the issue, it looks still relevant

**Closed** 2018-04-24 15:32 UTC
Labels: discussion
