### ISSUE TITLE
[Tisbury Treasure Hunt]: Feedback

### ISSUE THREAD

**Issue by chuck-alt-delete** [exercism/python#3068] opened 2022-05-27 18:22 UTC
Thanks as always for building Exercism! I have two pieces of feedback on tisbury-treasure-hunt:

### 1. Return None or raise error instead of "not a match" in create_record function

The `create_record` function says to return a record if coordinates match or the string "not a match" if the coordinates don't match. In my opinion, this encourages bad habits unnecessarily. I think instead, if there is no matching coordinate, the function should return none or should raise a `ValueError`.  At this point, learners aren't learning about error handling yet, so maybe just go with returning `None`.

### 2. The test for clean_up is inconsistent

Here is a solution that passes the tests:

```python
def clean_up(combined_record_group):
    """Clean up a combined record group into a multi-line string of single records.

    :param combined_record_group: tuple - everything from both participants.
    :return: str - everything "cleaned", excess coordinates and information are removed.

    The return statement should be a multi-lined string with items separated by newlines.

    (see HINTS.md for an example).
    """

    result = ""
    for record in combined_record_group:
        # hack to pass erroneous test
        if "Scrim" in record[0]:
            result += f"(\"{record[0]}\", \'{record[2]}\', {record[3]}, \'{record[4]}\')\n"
        else:
            result += f"(\'{record[0]}\', \'{record[2]}\', {record[3]}, \'{record[4]}\')\n"
    return result
```

Notice the special logic for the record that starts with "Scrim". It uses double quotes around record[0], whereas all the others use single quotes.

**Comment by BethanyG** [comment] 2022-06-02 16:59
Hi @chuck-alt-delete 👋🏽 

Thanks for the feedback, and for filing this issue!  💙  Apologies for the delay in getting back to you.

> Return None or raise error instead of "not a match" in create_record function.

For concept exercises, we're not permitted to use any language features that have not been introduced in a prior exercise or in the exercise itself, so raising an error here or _explicitly_ returning `None` is off the table.  However, we could have a student only return something if it's a match, and **not** return anything if there is no match  (_implicit_ return of `None`).  Not sure that's a better habit to teach.  

Python itself is all over the place.  `str.find()` returns `-1` when a substring is not found, and `str.index()` raises an error.   `dict[key]` raises an error, `dict.get()` returns `None`.  `list.index()` and `tuple.index()` raise errors.

So I could add in somewhere that returning a string sets a student up to later learn how to return an error with a message, or that when they reach the `None` concept (TBD) they learn that `None` is a really good replacement for a return value where you _don't_ want to raise an error.  But what I was really looking for here was a way to focus the student on `tuple` operations, and not overload the exercise with much of anything else, **so I think I am going to keep it as-is for now.**

<br>

> The test for clean_up is inconsistent

I would argue that the test for `clean_up` is very consistent (_maybe a bit too consistent_) -- students either return the expected string _exactly_ (quote style and all), or the test fails.  

What is _not_ consistent are the string quotes within the various `tuples`.  In particular, `("Scrimshaw Whale's Tooth", '2A')`, which uses double quotes so that the _single_ quote does not need escaping (_see the [Python docs tutorial](https://docs.python.org/3/tutorial/introduction.html#strings) for the many many string variations and escaping and processing caveats_).  

Students look at this "one thing is not like the other" and think they need to somehow cope with those double quotes.  **They don't**:

```python
 report = ""

    for item in combined_record_group:
        report += f"{(item[0], item[2], item[3], item[4])}\n"

    return report
```

That code will output a properly "escaped" string for the double-quoted string in the `tuple`:

`\"Scrimshaw Whale's Tooth\"`

The items inside `{(item[0], item[2], item[3], item[4])}` get processed **first**, then Python attempts to return a double-quoted string with the included `\n` characters, which means any existing `"` characters get escaped when the "final" string using `"""` is assembled.  

But  it does seem that many students are missing that.  And some are also using the unpack operator, which doesn't work in this scenario.  And most importantly, _**this is an exercise about `tuples` -  not about string formatting**_.

So I am going to either change the test data here to `'Scrimshawed Whale Tooth'`, or make the test case less precise (_"fuzzy"_) with regards to the quotes.  Having to explain the quoting lesson to students takes time, and the `str` lesson here is better it its own string formatting concept exercise. 😄

**Comment by chuck-confluent** [comment] 2022-06-02 17:07
Awesome, thanks for this thoughtful response, Bethany :-)

**Comment by FranciscoRguezMelgar** [comment] 2022-06-02 20:23
It seems, if I have understood correctly, that the problem is that the test expects the students to rely on Python's serialization of tuples with strings inside, which will prefer the string quotation that won't requiere scaping when printed. While one could think that the simple quotations around the fields of the strings are part of the format that the test requires. To avoid that, a solution that does not include any quotations in the resulting string would be preferred, therefore, instead of the code you showed us, one could use something like the original asker without the conditional but without the simple quotations around the items of the tuple.

From a personal standpoint, I think many of us simply try to use the same kind of quotes always because we have worked with technologies where serialization is not provided by a standard library and making parsers of our own is easier when we know exactly the kind of quote used.

PS. Thanks for your lengthy and complete explanation.

**Comment by BethanyG** [comment] 2022-06-02 23:46
Closing now that #3072 has been merged.

**Closed by BethanyG** 2022-06-02 23:46 UTC
