### ISSUE TITLE
lists_test.py in card-games exercise has a wrong answer in the test.

### ISSUE THREAD

**Issue by toastin0** [exercism/python#2522] opened 2021-09-02 00:05 UTC
Hey! sorry to bother you, but i'm pretty sure i found a bug in the test for the card games exercise. In the TestApproxAverageIsAverage, test_instructions_example_2's mean is 5, and the median is 4. However, it wants to evaluate to true, meaning that the mean and the median are the same. If this is intentional, i'm sorry for the inconvenience.

**Comment by kbuc** [comment] 2021-09-02 18:45
Not a bug.

Note that the exercise gives **two** possible ways of calculating the alternative average: 
"by taking the average of the first and last card values in the hand - or by using the "middle" card value (the median) of the hand."

In this particular test the first option is the right one, the average of first and last element (2 and 8) is 5, which is the same as mean.

**Comment by BethanyG** [comment] 2021-09-02 19:56
@kbuc  -- Excellent point!  Thank you for responding to this.  I think I am going to close this, but on looking at the, [stub](https://github.com/exercism/python/blob/main/exercises/concept/card-games/lists.py) and [exemplar](https://github.com/exercism/python/blob/main/exercises/concept/card-games/.meta/exemplar.py) files for this exercise, there is a bug with the `docstrings` that imply that `approx_average_is_average(hand)` should `return` an `int`.  I will log that as a different issue.  Feel free to pick it up, if you want another quick PR.  😄

**Comment by BethanyG** [comment] 2021-09-02 19:58
@toastin0 - @kbuc  is correct, the exercise is to test either method.  So the testing is correct.  But please do feel free to open a separate issue if you think the instructions are confusing or misleading.  Thanks!

**Closed by BethanyG** 2021-09-02 19:58 UTC

**Comment by toastin0** [comment] 2021-09-02 20:00
Ah, I see! Next time, I'll read more before I open an issue. Thank you for your time, and apologies for the inconvenience!
