### ISSUE TITLE
Travis HOUSEKEEPING job: handle multiple out-of-date exercises

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1920] opened 2019-09-19 15:05 UTC
See https://travis-ci.org/exercism/python/jobs/586880990

**Comment by cmccandless** [comment] 2020-01-17 15:09
One possible solution to keep CI from blocking PRs due to unrelated changes in another repository would be to only check modified exercises in the HOUSEKEEPING job. The CANONICAL_SYNC job already checks if exercises are up-to-date (though only the version is checked), and this job is not required to pass the build.

@exercism/python, thoughts?

**Comment by paparomeo** [comment] 2020-01-17 18:50
>  [...] due to unrelated changes in another repository [...]
Did you mean "[...] due to unrelated changes in another _exercise_ [...]"? Otherwise, I'm not exactly following what the problem is. :confused:

**Comment by cmccandless** [comment] 2020-01-17 19:03
> Did you mean "[...] due to unrelated changes in another exercise [...]"? Otherwise, I'm not exactly following what the problem is. confused

Technically, it's both. The canonical data is stored in exercism/problem-specifications (a separate repository).

However, the format of things may change with the conversion to v3, so it's possible that this issue will just disappear (or change into something else) anyway.

**Comment by paparomeo** [comment] 2020-01-17 19:22
Ah yes, I get it now. Thanks for the clarification.

**Comment by BethanyG** [comment] 2021-02-15 17:53
@cmccandless  -- I think with our move to GH Actions, your CI re-write, and our V3 re-org this issue is no longer relevant.  I'm going to close this -- just let me know if I need to re-open.  Thanks!

**Closed by BethanyG** 2021-02-15 17:53 UTC
Labels: canonical-sync
