### ISSUE TITLE
Missing init code for test scripts

### ISSUE THREAD

**Issue by shumashv1** [exercism/python#2717] opened 2021-11-02 15:20 UTC
Test scripts import both pytest and unittest.  I run code locally in the Spyder GUI, and tests don't execute until I add initiator lines.  If I add an initiator to the last lines of the script (as previous test scripts have done) as follows:

if name == "main":
pytest.main()

 -or-

if name == "main":
unittest.main()

the tests run.  Running the tests from the command line also works with:
python -m unittest <filename>_test.py -or- python -m pytest <filename>_test.py

**Comment by IsaacG** [comment] 2021-11-02 21:16
This is working as intended.

Per the [Python testing docs](https://exercism.org/docs/tracks/python/tests), you should be able to configure your editor to run tests using `pytest` or `python3 -m pytest`. That's the intended workflow. 

Running the test file directly as an executable script is not the intended or supported workflow. The Python maintainers have been explicitly removing the `if __name__ == "__main__"` stanzas from the Python test files as we do not want students going that route.

**Comment by shumashv1** [comment] 2021-11-03 02:29
OK, I’ll buy that, but when I go to the Testing docs link and attempt to look into Tools, I get this:

https://exercism.org/docs/tracks/python/TOOLS.md
***@***.***
Not very helpful.

**Comment by IsaacG** [comment] 2021-11-03 02:43
You're absolutely right. Thanks for calling that out. I filed https://github.com/exercism/python/issues/2721 to fix that.

You can view the TOOLS.md [directly in Github](https://github.com/exercism/python/blob/main/docs/TOOLS.md) in the meanwhile.

**Comment by BethanyG** [comment] 2021-11-03 03:10
@shumashv1 

The details in this issue may be of help.  Spyder actually has an add-in that will allow you to run pytest files.  However, if you have Spyder 5, I don't know that the plugin works.  The other details in the issue address various ways to invoke Pytest from iPython/Spyder.  https://github.com/exercism/exercism/issues/5791.

We'll get the linking issues with the testing/tooling docs fixed shortly.

**Comment by shumashv1** [comment] 2021-11-03 12:03
Thanks for the response. Very helpful.

**Comment by shumashv1** [comment] 2021-11-03 12:12
Thanks. Very helpful.

**Comment by BethanyG** [comment] 2021-11-03 17:10
@shumashv1  - very happy that helped!

I am going to close this issue as resolved.  Please feel free to open another, should you need help, have a question, or spot a bug.  🌟 

The publishing/links problem you encountered is logged as issue #2721 .

**Closed by BethanyG** 2021-11-03 17:10 UTC
