### ISSUE TITLE
Copying the Ruby track structure

### ISSUE THREAD

**Issue by iHiD** [exercism/python#1614] opened 2018-12-03 14:20 UTC
Hello @exercism/python 

Python is one of two tracks that we're really struggling to mentor. The main reason seems to be that the structure of the track isn't massively easy for beginners to upramp on, so mentors are having to solve a *lot* of issues on each exercise. 

We're currently working on a project to build a system to make structuring tracks easier. We'd like to work on the Python track for that as soon as it's ready. However, in the meantime, I think we should re-order exercises to be the same as in Ruby, which has had a huge amount of effort put into it in terms of thinking about structure.

If anyone massively disagrees then please speak up. Otherwise we'll do this in the next week or so. If anyone would like to volunteer to do the PR for this, then that would be super helpful, otherwise I'm tentatively assigning this to @kytrinyx .

**Comment by yawpitch** [comment] 2018-12-03 14:53
A lot of the exercises in the core Ruby track will have a significant amount over overlap in the Python track.

Personally I would eliminate `two-fer` entirely; I'd rather see the ability to handle a default argument be a bonus challenge on `hello-world`, and plenty of the other exercises have string formatting and concatenation.

I would ten to put `isogram` before `acronym`, 

The `raindrops` exercise has already been deprecated in Python and I wouldn't bring it back. It again has a lot of overlap with exercises above it and we really don't want to front-load just string methods in all the exercises.

I would suggest we keep `leap` and `book-store` and `binary-search`, while I wouldn't consider `twelve-days` or any of the other "song" ones for inclusion.

**Comment by iHiD** [comment] 2018-12-03 14:58
@yawpitch Superhelpful. Thanks. The point of two-fer in Ruby is to teach the very simple things like indenting (two spaces), conditionals, etc. The default argument is in many ways incidental to the point of the exercise. Is there another exercise that is as simple as two-fer that could achieve the same thing?

**Comment by yawpitch** [comment] 2018-12-03 14:58
Also I'll add in a vote for `sieve` and `run-length-encoding` both being better core exercises than `rest-api`, which I would argue really isn't ready for prime time, much less core.

**Comment by yawpitch** [comment] 2018-12-03 15:03
@iHiD though I personally dislike `bob`, I think it covers all those bases for Python; it requires proper indentation and introduces simple control flow with **if** and **elif**; I'd say it's certainly more useful than `two-fer` at weeding out those issues.

**Comment by yawpitch** [comment] 2018-12-03 15:07
I'd be happy to see `kindergarten-garden` and `allergies` leave core ... they both soak up quite a bit of time and again have a lot of overlap one with the other ... if I were to keep either it would _definitely_ be `allergies` because it introduces _bitwise operators_  -- quite possibly the least reached for tool in the Python standard lib -- but I don't think that's enough to save it.

**Comment by rpalo** [comment] 2018-12-03 15:30
Personally, I'm OK with Two-Fer -- it's a good confidence builder, but it's weird that it's so far back in the course.  Should probably be right after Hello World.

While I like both Kindergarten Garden and Allergies, I agree that they're very similar.  I agree that allergies would be a good one to be core, because if it was a side-exercise, I'm pretty sure a big segment of the students who try it would miss the binary entirely.  Kindergarten garden's gotchas could be picked up as community comments on a side exercise probably.

I personally really hate mentoring Book Store.  However, it's a good exercise, I enjoyed it when I went through it on the track, and I really benefited from having a mentor there.  But maybe it would be ok to leave as a side exercise that people could opt into?

I *really* like Markdown and REST API as core exercises.  They're kind of like the track master's theses, or, at least, that's what it feels like as both a student and a mentor on them.  They present a little bit of design/architecture thinking as well as the idiomatic Python stuff.

I'd have to comb through the side exercises to see if I think they would be good core ones, but, overall, I think you probably couldn't go wrong with mirroring the Ruby track for most things.  It feels well-laid-out and each exercise introduces something important and new.

**Comment by iHiD** [comment] 2018-12-03 15:52
> Personally, I'm OK with Two-Fer -- it's a good confidence builder

This is my strong feeling too. I feel like it is a nice gentle step up from Hello World, gives mentors the first opportunity to iron out newbie problems (inconsistent indenting, weird variable names, etc), and in 50% of cases can be approved in 20secs.

**Comment by cmccandless** [comment] 2018-12-03 15:56
> in 50% of cases can be approved in 20secs.

Do we actually have/track this metric (or is it anecdotal)? If so, that's awesome!

**Comment by iHiD** [comment] 2018-12-03 16:03
It's anecdotical but I've mentored >50 twofers and so I think it's a pretty authoritative anecdote :) @kytrinyx has similar experience in her tracks and @ErikSchierboom in his.

**Comment by yawpitch** [comment] 2018-12-03 16:05
I suppose my issue with `two-fer` is that it's basically `hello-world` with the added twist of a default argument ... if we actually verified that `hello-world` passed the test we'd eliminate most of the problems you're describing as well, and such problems are currently being addressed in `leap` with just one iteration as is.

That said part of my issue with it is that -- where it's currently placed in the order -- if it takes more than 2 seconds to approve, it's too much.

**Comment by yawpitch** [comment] 2018-12-03 16:12
Right ... personal bias then. I'm now pretty certain I'm among the world's foremost experts on "what is a bloody leap year", but I'll readily admit I'd prefer to not have to walk so many complete beginners through 6-7 iterations on it, with 3-4 just on basic setup issues.

I remove my objection to `two-fer` ...

**Comment by cmccandless** [comment] 2018-12-03 16:16
> I remove my objection to two-fer ...

Seconded. I don't currently mentor, so I don't have that personal perspective. Thanks @iHiD.

**Comment by yawpitch** [comment] 2018-12-03 16:16
As for `markdown` and `rest-api`, I too like the "thesis" projects ... but I personally think either `forth` or `react` are both more fully fleshed out, better described, and cover a broader range of topics than `rest-api`.

**Comment by kytrinyx** [comment] 2018-12-03 16:19
> Personally, I'm OK with Two-Fer -- it's a good confidence builder, but it's weird that it's so far back in the course. Should probably be right after Hello World.

Two-Fer is kind of the perfect exercise to have right after Hello World (at least in most tracks). That's what it was intended to be. It has a single conditional, and is a good opportunity to talk about style things without blocking their progress. I've found that it gets a lot of people progressing without taking up too much mentor time, at least in the Go track where it's directly after hello world.

**Comment by yawpitch** [comment] 2018-12-03 17:06
Yeah, in modern Python it's most sensibly implemented like so:

```python
def two_fer(name="you"):
    return f'One for {name}, one for me."
```

Compare that with a decent`hello-world`:

```python
def hello_world(name="World"):
    return f'Hello, {name}!"
```

And you see my reasoning.

But I do see the advantage since `hello-world` is automatically approved.

**Comment by yawpitch** [comment] 2018-12-03 17:10
Yeah, in modern Python it's most sensibly implemented like so:

```python
def two_fer(name="you"):
    return f'One for {name}, one for me."
```

Compare that with a decent`hello-world`:

```python
def hello_world(name="World"):
    return f'Hello, {name}!"
```

And you see my reasoning.

**Comment by cmccandless** [comment] 2018-12-03 17:47
I do see your reasoning. The only issue I take with it is that `hello-world` is meant to be as simple as possible: no optional parameters, no string interpolation, etc. Just "Hello, World!"

**Comment by yawpitch** [comment] 2018-12-03 17:53
True, just noticed that a whole bunch of people go for the reach goal, in all the tracks. And default arguments and string formatting are well covered by other exercises that offer more.

Regardless, if it's the second exercise I've got no objection... right now it's positioned in such a way in Core that anyone that reaches it feels like their time is being wasted.

**Comment by iHiD** [comment] 2018-12-17 15:40
Just making https://github.com/exercism/python/pull/1633 visible to contributors to this thread.

**Closed** 2018-12-18 15:22 UTC
Labels: discussion, enhancement, help wanted
