### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by viperblack** [exercism/python#3049] opened 2022-05-12 20:46 UTC
On exercise [[Card Games in Python]](https://exercism.org/tracks/python/exercises/card-games) on file lists_test.py (line 76) the list for correct assertion be True is [2, 3, 5, 7, 8] and not [2, 3, 4, 8, 8] where median is 4 and mean is 5.

**Comment by IsaacG** [comment] 2022-05-16 20:42
The instructions read:
> Return `True` if either _one_ `or` _both_ of the, above named, strategies result in a number _equal_ to the _actual average_.

The mean of the list is 5. The mean of the first and last value is 5. Hence the approximate average is equal to the average.

**Comment by BethanyG** [comment] 2022-05-16 21:33
Hi @viperblack 👋🏽 

Thanks for filing this issue.  As @IsaacG has stated above, the task is asking for an `OR` situation.  **One `OR` the other `OR` both**, as opposed to "One `AND` the other".  The test case you cite was added purposefully to get at this particular scenario, and is not a bug.  I am going to go ahead and close this issue, but please let us know if you have any additional questions or issues.  We can re-open this, or file a new one.

**Closed by BethanyG** 2022-05-16 21:33 UTC

**Comment by viperblack** [comment] 2022-05-17 18:09
Thanks @IsaacG and @BethanyG for instructions! I pay attention in the next time.
